function deleteApplicant(id){const row=S.applicants.find(x=>x.id===id);showConfirm({title:'지원자를 삭제할까요?',text:`${row?.name||'선택한 지원자'}의 정보${row?.reserved?'와 예약':''}를 삭제합니다.`,confirmText:'삭제',danger:true,onConfirm:async()=>{showLoading('지원자 삭제 중','잠시만 기다려주세요.');await api('/admin/applicants',{method:'DELETE',body:JSON.stringify({id})});await refresh();showResult('success','삭제 완료',`${row?.name||'지원자'}을(를) 삭제했습니다.`)}})}
function deleteSlot(id){const row=S.slots.find(x=>x.id===id);showConfirm({title:'면접 슬롯을 삭제할까요?',text:`${row?D(row.starts_at)+' '+T(row.starts_at)+' ~ '+T(row.ends_at):'선택한 슬롯'}을 삭제합니다.${row?.reserved?' 예약된 지원자의 예약도 해제됩니다.':''}`,confirmText:'삭제',danger:true,onConfirm:async()=>{showLoading('면접 슬롯 삭제 중','잠시만 기다려주세요.');await api('/admin/slots',{method:'DELETE',body:JSON.stringify({id})});await refresh();showResult('success','삭제 완료','면접 슬롯을 삭제했습니다.')}})}
function bindSlotRows(){document.querySelectorAll('.editableCell').forEach(td=>td.onclick=()=>startInlineEdit(td));document.querySelectorAll('.ds').forEach(b=>b.onclick=()=>deleteSlot(b.dataset.id))}
async function askSlotDeletion({mode,date=null,title,text,confirmText='삭제',requireText='',doneTitle='삭제 완료'}){try{showLoading('삭제 대상 확인 중','현재 서버 데이터를 기준으로 계산하고 있습니다.');const preview=await api('/admin/slots-preview',{method:'POST',body:JSON.stringify({mode,date})});if(!preview.slotCount)return showResult('success','삭제 대상 없음','조건에 맞는 면접 슬롯이 없습니다.');const payload={...(mode==='cutoffEmpty'?{cutoffEmpty:true}:mode==='all'?{all:true}:{date,includeReserved:mode==='dayAll'}),expectedSlotCount:preview.slotCount,expectedReservationCount:preview.reservationCount};showConfirm({title,text,summary:`삭제 슬롯: <b>${preview.slotCount}개</b><br>연결 예약·면접 기록: <b>${preview.reservationCount}건</b><br>빈 슬롯: <b>${preview.emptyCount}개</b>${date?`<br>대상 날짜: <b>${E(date)}</b>`:''}`,confirmText,danger:true,requireText,onConfirm:async()=>{showLoading('면접 슬롯 삭제 중','삭제 전 상태를 복구 기록에 저장하고 있습니다.');const result=await api('/admin/slots',{method:'DELETE',body:JSON.stringify(payload)});if(mode==='all')adminSelectedDay=null;await refresh();showResult('success',doneTitle,`면접 슬롯 ${result.deletedCount||0}개${result.reservationCount?`와 연결 예약 ${result.reservationCount}건`:''}을 삭제했습니다. 최근 삭제에서 복구할 수 있습니다.`)}})}catch(x){showResult('error','대상 확인 실패',x.message)}}
function restoreTrash(id){const item=(S.trash||[]).find(x=>x.id===id);if(!item)return;showConfirm({title:'삭제한 슬롯을 복구할까요?',text:'삭제 당시의 슬롯과 연결 예약을 함께 복구합니다. 현재 데이터와 충돌하면 복구하지 않습니다.',summary:`${E(trashKind(item.kind))}${item.label?` · <b>${E(item.label)}</b>`:''}<br>슬롯: <b>${Number(item.slot_count)||0}개</b><br>예약 기록: <b>${Number(item.reservation_count)||0}건</b>`,confirmText:'복구',onConfirm:async()=>{showLoading('복구 중','삭제 당시 상태를 확인하고 있습니다.');const result=await api('/admin/slot-trash',{method:'POST',body:JSON.stringify({batchId:id})});await refresh();showResult('success','복구 완료',`슬롯 ${result.restoredSlotCount||0}개와 예약 ${result.restoredReservationCount||0}건을 복구했습니다.`)}})}
function bind(){
 document.getElementById('alo').onclick=async()=>{await api('/admin/logout',{method:'POST'});aLogin()};
 document.getElementById('sdf').onchange=()=>{const a=document.getElementById('sdf'),b=document.getElementById('sdt');if(!b.value||b.value<a.value)b.value=a.value};
 document.getElementById('sf').onsubmit=e=>{e.preventDefault();let p;try{p=creationPlan()}catch(x){return showResult('error','입력값 확인',x.message)};showConfirm({title:'면접 슬롯을 생성할까요?',text:'아래 일정으로 면접 슬롯을 일괄 생성합니다.',summary:`<b>${E(p.from)} ~ ${E(p.to)}</b><br>${E(p.start)} ~ ${E(p.end)} · ${p.minutes}분 간격<br>${p.days}일 × ${p.perDay}개 = <b>총 ${p.total}개</b><br>장소: <b>${E(p.location)}</b>`,confirmText:'생성',onConfirm:()=>createSlots(p)})};
 document.getElementById('cutoffForm').onsubmit=e=>{e.preventDefault();const h=Number(document.getElementById('cutoffHours').value);if(!Number.isInteger(h)||h<0||h>720)return showResult('error','입력값 확인','마감 시간은 0~720시간 사이 정수로 입력해주세요.');showConfirm({title:'예약 마감 시간을 변경할까요?',text:`면접 시작 ${h}시간 전부터 지원자의 신규 예약·변경·취소가 제한됩니다.`,confirmText:'저장',onConfirm:async()=>{showLoading('설정 저장 중','잠시만 기다려주세요.');await api('/admin/settings',{method:'POST',body:JSON.stringify({cutoffHours:h})});await refresh();showResult('success','저장 완료',`예약 마감 시간이 면접 시작 ${h}시간 전으로 설정되었습니다.`)}})};
 document.getElementById('uf').onsubmit=async e=>{e.preventDefault();const text=document.getElementById('ut').value;try{const r=await api('/admin/applicants',{method:'POST',body:JSON.stringify({text})});await refresh();setMessage(`${r.count||0}명의 지원자 등록을 처리했습니다.`,'success')}catch(x){setMessage(x.message,'error')}};
 document.getElementById('dua').onclick=()=>showConfirm({title:'지원자를 모두 삭제할까요?',text:'등록된 지원자와 관련 예약 정보가 함께 삭제되며 되돌릴 수 없습니다.',confirmText:'전체 삭제',danger:true,onConfirm:async()=>{showLoading('지원자 삭제 중','잠시만 기다려주세요.');await api('/admin/applicants',{method:'DELETE',body:JSON.stringify({all:true})});await refresh();showResult('success','삭제 완료','등록된 지원자를 모두 삭제했습니다.')}});
 document.getElementById('cleanupPast').onclick=()=>askSlotDeletion({mode:'cutoffEmpty',title:'마감 지난 빈 슬롯을 정리할까요?',text:`현재 예약 마감 기준은 면접 시작 ${Number(S.cutoffHours)||0}시간 전입니다. 오늘과 지난 날짜의 빈 슬롯만 정리하며, 다음 날짜와 예약 슬롯은 유지합니다.`,confirmText:'정리',doneTitle:'정리 완료'});
 document.getElementById('dsa').onclick=()=>askSlotDeletion({mode:'all',title:'면접 슬롯을 모두 삭제할까요?',text:'빈 슬롯뿐 아니라 예약자가 있는 슬롯과 연결된 예약·면접 기록도 모두 삭제됩니다. 삭제 전 상태는 최근 삭제에 보관됩니다.',confirmText:'전체 삭제',requireText:'전체 삭제',doneTitle:'전체 삭제 완료'});
 document.getElementById('deleteDayEmpty')?.addEventListener('click',()=>askSlotDeletion({mode:'dayEmpty',date:adminSelectedDay,title:'선택한 날짜의 빈 슬롯을 삭제할까요?',text:'선택 날짜의 빈 슬롯만 삭제하며 예약자가 있는 슬롯은 유지합니다.',confirmText:'빈 슬롯 삭제'}));
 document.getElementById('deleteDayAll')?.addEventListener('click',()=>askSlotDeletion({mode:'dayAll',date:adminSelectedDay,title:'선택한 날짜의 슬롯을 모두 삭제할까요?',text:'선택 날짜의 빈 슬롯과 예약 슬롯, 연결된 면접 기록을 모두 삭제합니다.',confirmText:'날짜 전체 삭제'}));
 document.querySelectorAll('.restoreTrash').forEach(b=>b.onclick=()=>restoreTrash(b.dataset.id));
 document.querySelectorAll('.du').forEach(b=>b.onclick=()=>deleteApplicant(b.dataset.id));document.querySelectorAll('.manage').forEach(b=>b.onclick=()=>manage(b.dataset.id));bindSlotRows();
 document.querySelectorAll('.adminDateTab').forEach(b=>b.onclick=()=>{adminSelectedDay=b.dataset.day;document.querySelectorAll('.adminDateTab').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('selectedDayLabel').textContent=adminSelectedDay;document.getElementById('adminSlotTable').innerHTML=slotTable(adminSlotsByDay()[adminSelectedDay]||[]);bindSlotRows()});
 requestAnimationFrame(()=>{const bar=document.getElementById('adminDateTabs'),active=bar?.querySelector('.adminDateTab.active');if(bar&&active)bar.scrollLeft=Math.max(0,active.offsetLeft-(bar.clientWidth-active.clientWidth)/2)});
}
