function uLogin(){app.innerHTML=`<main class="wrap">${LOGO}<section class="card"><h1>면접 시간 예약</h1><p class="muted">이름과 전화번호 뒷 4자리로 확인해주세요.</p><form id="f"><div class="field"><label>이름</label><input id="n"></div><div class="field"><label>전화번호 뒷 4자리</label><input id="p" maxlength="4" inputmode="numeric"></div><p id="m" class="err"></p><button class="btn" style="width:100%">면접 시간 선택하기</button></form></section></main>`;document.getElementById('f').onsubmit=async e=>{e.preventDefault();try{await api('/login',{method:'POST',body:JSON.stringify({name:document.getElementById('n').value,last4:document.getElementById('p').value})});user()}catch(x){document.getElementById('m').textContent=x.message}}}
async function user(){try{
  let d=await api('/reservations');
  if(!d?.applicant?.name){try{await api('/logout',{method:'POST'})}catch{}userSelectedDay=null;return uLogin()}
  d.slots=Array.isArray(d.slots)?d.slots:[];
  const g={};d.slots.forEach(s=>(g[D(s.starts_at)]??=[]).push(s));
  const days=Object.keys(g),currentDay=d.current?D(d.current.starts_at):null;
  if(currentDay&&!userSelectedDay)userSelectedDay=currentDay;
  if(!userSelectedDay||!g[userSelectedDay])userSelectedDay=days.find(day=>g[day].some(s=>!s.reserved&&!s.locked))||days[0]||null;
  const cutoffText=d.cutoffHours>0?`면접 ${d.cutoffHours}시간 전부터 신규 예약·시간 변경·취소가 마감됩니다.`:'예약 변경 마감 제한이 없습니다.';
  const tabs=days.map(day=>{const ss=g[day],available=ss.filter(s=>!s.reserved&&!s.locked).length;return `<button class="dateTab ${day===userSelectedDay?'active':''}" data-day="${E(day)}"><span>${DT(ss[0].starts_at)}</span><small>${available>0?`${available}개 가능`:'마감'}</small></button>`}).join('');
  const renderDay=day=>{const ss=g[day]||[];if(!ss.length)return '<section class="card muted">선택한 날짜에 등록된 면접 시간이 없습니다.</section>';return `<section class="card"><div class="daySlotsTitle"><b>${E(day)}</b><span class="muted" style="font-size:12px">${ss.length}개 슬롯</span></div>${ss.map(s=>{const unavailable=(s.reserved&&!s.mine)||s.locked,label=s.mine?(s.locked?'내 예약 · 변경 마감':'내 예약'):s.reserved?'예약 마감':s.locked?'신청 마감':'예약 가능';return `<button class="slot ${s.mine?'mine':''}" data-id="${s.id}" ${unavailable?'disabled':''}><span><b>${T(s.starts_at)} ~ ${T(s.ends_at)}</b><br><small class="muted">${label}</small><br><small class="muted">장소: ${E(s.location||'AI공학관')}</small></span><b>${s.mine?'✓':''}</b></button>`}).join('')}</section>`};
  app.innerHTML=`<main class="wrap">${LOGO}<div class="title"><div><h1>${E(d.applicant.name)}님</h1><p class="muted">원하는 면접 시간을 선택해주세요.</p></div><button id="lo" class="btn sec sm">로그아웃</button></div><p class="muted cutoffNotice">${cutoffText}</p><p class="muted cutoffNotice">※ 면접 장소는 면접 시작 12시간 전에 최종 업데이트됩니다. 면접 전에 다시 한 번 확인해주세요.</p>${d.current?`<section class="card current"><b>현재 예약</b><p>${D(d.current.starts_at)} ${T(d.current.starts_at)} ~ ${T(d.current.ends_at)}</p><p><b>면접 장소</b><br>${E(d.current.location||'AI공학관')}</p>${d.currentLocked?`<div class="lockedHint">면접 ${d.cutoffHours}시간 전부터는 예약 시간을 변경하거나 취소할 수 없습니다.</div><button class="btn danger" style="width:100%;margin-top:10px" disabled>변경/취소 마감</button>`:`<button id="can" class="btn danger" style="width:100%">예약 취소</button>`}</section>`:''}<p id="um" class="err"></p>${days.length?`<nav id="dateTabs" class="dateTabs" aria-label="면접 날짜 선택">${tabs}</nav><div id="daySlots">${renderDay(userSelectedDay)}</div>`:'<section class="card muted">아직 등록된 면접 시간이 없습니다.</section>'}</main>`;
  document.getElementById('lo').onclick=async()=>{await api('/logout',{method:'POST'});userSelectedDay=null;uLogin()};
  if(d.current&&!d.currentLocked)document.getElementById('can').onclick=async()=>{if(confirm('현재 예약을 취소할까요? 취소 후에는 다른 지원자가 해당 시간을 예약할 수 있습니다.'))try{await api('/reservations',{method:'POST',body:JSON.stringify({action:'cancel'})});user()}catch(x){document.getElementById('um').textContent=x.message}};
  const bindSlots=()=>document.querySelectorAll('.slot:not(:disabled)').forEach(btn=>btn.onclick=async()=>{const s=d.slots.find(x=>x.id===btn.dataset.id);if(s?.mine)return;if(!confirm(d.current?'선택한 시간으로 면접 예약을 변경할까요?':'선택한 시간으로 면접을 예약할까요?'))return;try{userSelectedDay=D(s.starts_at);await api('/reservations',{method:'POST',body:JSON.stringify({action:d.current?'change':'reserve',slotId:btn.dataset.id})});user()}catch(x){document.getElementById('um').textContent=x.message}});
  bindSlots();
  document.querySelectorAll('.dateTab').forEach(btn=>btn.onclick=()=>{userSelectedDay=btn.dataset.day;document.querySelectorAll('.dateTab').forEach(x=>x.classList.toggle('active',x===btn));document.getElementById('daySlots').innerHTML=renderDay(userSelectedDay);bindSlots()});
  requestAnimationFrame(()=>{const bar=document.getElementById('dateTabs'),active=bar?.querySelector('.dateTab.active');if(bar&&active)bar.scrollLeft=Math.max(0,active.offsetLeft-(bar.clientWidth-active.clientWidth)/2)});
}catch(x){x.status===401?uLogin():app.innerHTML='<main class="wrap"><p class="err">'+E(x.message)+'</p></main>'}}
