const C=require('./core');
async function login(req,res){try{if(req.method!=='POST')return C.json(res,405,{error:'허용되지 않은 요청입니다.'});const b=C.body(req)||{},name=C.normalizeName(b.name),last4=String(b.last4??'').trim();if(!name||name.length>40||!/^[0-9]{4}$/.test(last4))return C.json(res,400,{error:'입력한 정보를 확인해주세요.'});const {data,error}=await C.supabase().from('applicants').select('id').eq('name',name).eq('phone_last4_hash',C.hashLast4(last4)).maybeSingle();if(error)throw error;if(!data)return C.json(res,401,{error:'입력한 정보를 확인해주세요.'});C.setApplicantSession(res,data.id);return C.json(res,200,{ok:true})}catch(e){C.fail(res,e)}}
function logout(req,res){C.clearApplicantSession(res);return C.json(res,200,{ok:true})}
async function reservations(req,res){try{const appId=C.applicantId(req);if(!appId)return C.json(res,401,{error:'로그인이 필요합니다.'});const {data:app,error:ae}=await C.supabase().from('applicants').select('id,name').eq('id',appId).maybeSingle();if(ae)throw ae;if(!app){C.clearApplicantSession(res);return C.json(res,401,{error:'로그인이 필요합니다.'})}const cutoff=await C.getCutoff();
 if(req.method==='GET'){const now=new Date().toISOString();const [{data:slots,error:se},{data:rs,error:re}]=await Promise.all([C.supabase().from('interview_slots').select('id,starts_at,ends_at,note,location').gt('starts_at',now).order('starts_at'),C.supabase().from('reservations').select('applicant_id,slot_id')]);if(se||re)throw se||re;const bySlot=new Map((rs||[]).map(r=>[r.slot_id,r.applicant_id]));const mapped=(slots||[]).map(s=>({id:s.id,starts_at:s.starts_at,ends_at:s.ends_at,location:s.location||'AI공학관',reserved:bySlot.has(s.id),mine:bySlot.get(s.id)===appId,locked:C.isLocked(s.starts_at,cutoff)}));let current=null,currentLocked=false;const cr=(rs||[]).find(r=>r.applicant_id===appId);if(cr){let s=(slots||[]).find(x=>x.id===cr.slot_id);if(!s)s=await C.targetSlot(cr.slot_id);if(s){current={id:s.id,starts_at:s.starts_at,ends_at:s.ends_at,location:s.location||'AI공학관'};currentLocked=C.isLocked(s.starts_at,cutoff)||new Date(s.starts_at).getTime()<=Date.now()}}return C.json(res,200,{applicant:app,slots:mapped,current,currentLocked,cutoffHours:cutoff})}
 if(req.method!=='POST')return C.json(res,405,{error:'허용되지 않은 요청입니다.'});const b=C.body(req)||{},action=String(b.action||'');if(action==='cancel'){const cr=await C.currentReservation(appId);if(!cr)return C.json(res,409,{error:'취소할 예약이 없습니다.'});if(C.isLocked(cr.slot.starts_at,cutoff)||new Date(cr.slot.starts_at).getTime()<=Date.now())return C.json(res,409,{error:`면접 ${cutoff}시간 전부터는 예약을 취소할 수 없습니다.`});const {error}=await C.supabase().from('reservations').delete().eq('applicant_id',appId);if(error)throw error;return C.json(res,200,{ok:true})}
 if(!['reserve','change'].includes(action))return C.json(res,400,{error:'잘못된 요청입니다.'});const slot=await C.targetSlot(b.slotId);if(!slot||new Date(slot.starts_at).getTime()<=Date.now())return C.json(res,400,{error:'예약할 수 없는 시간입니다.'});if(C.isLocked(slot.starts_at,cutoff))return C.json(res,409,{error:`면접 ${cutoff}시간 전부터는 해당 시간을 예약할 수 없습니다.`});const cr=await C.currentReservation(appId);if(action==='reserve'&&cr)return C.json(res,409,{error:'이미 예약한 시간이 있습니다.'});if(action==='change'&&!cr)return C.json(res,409,{error:'변경할 기존 예약이 없습니다.'});if(action==='change'&&(C.isLocked(cr.slot.starts_at,cutoff)||new Date(cr.slot.starts_at).getTime()<=Date.now()))return C.json(res,409,{error:`면접 ${cutoff}시간 전부터는 기존 예약을 변경할 수 없습니다.`});
 if(action==='reserve'){const {error}=await C.supabase().from('reservations').insert({applicant_id:appId,slot_id:slot.id});if(error){if(error.code==='23505')return C.json(res,409,{error:'방금 다른 지원자가 이 시간을 예약했습니다. 다른 시간을 선택해주세요.'});throw error}}else{const {error}=await C.supabase().from('reservations').update({slot_id:slot.id}).eq('applicant_id',appId);if(error){if(error.code==='23505')return C.json(res,409,{error:'방금 다른 지원자가 이 시간을 예약했습니다. 기존 예약은 유지됩니다.'});throw error}}return C.json(res,200,{ok:true})
 }catch(e){C.fail(res,e)}}
module.exports={login,logout,reservations};
